apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: kubernate
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2026-05-22T09:50:39Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
  name: data-postgres-postgresql-0
  namespace: default
  resourceVersion: "1814"
  uid: 51baef90-e8b9-4fe6-a045-abb7404f43bc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-51baef90-e8b9-4fe6-a045-abb7404f43bc
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound